# -*- mode: python ; coding: utf-8 -*-
block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[],
    hiddenimports=[
        'app',
        'app.core',
        'app.gui',
        'app.gui.panels',
        'app.i18n',
        'app.logger',
        'app.core.config_manager',
        'app.core.prompt_generator',
        'app.core.ai_mapper',
        'app.core.video_builder',
        'app.gui.theme',
        'app.gui.widgets',
        'app.gui.main_window',
        'app.gui.panels.dashboard',
        'app.gui.panels.settings_panel',
        'app.gui.panels.style_panel',
        'app.gui.panels.pipeline_panel',
        'app.gui.panels.outputs_panel',
        'groq',
        'groq._client',
        'moviepy',
        'moviepy.editor',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'PIL.ImageFont',
        'pydub',
        'google.generativeai',
        'huggingface_hub',
        'numpy',
        'requests',
        'PySide6.QtCore',
        'PySide6.QtWidgets',
        'PySide6.QtGui',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter', 'matplotlib', 'scipy', 'jupyter',
        'torch', 'torchvision', 'torchaudio',
        'numba', 'llvmlite',
        'IPython', 'notebook', 'nbformat', 'nbconvert',
        'sklearn', 'sklearn',
        'pandas', 'pyarrow',
        'tensorflow', 'keras',
        'cv2', 'skimage',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='AutoCut',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    icon='autocut.ico',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='AutoCut',
)
